# Form implementation generated from reading ui file '/Users/dima/PycharmProjects/LoginSystem/widget/DialogForgot.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.email_le = QtWidgets.QLineEdit(parent=Dialog)
        self.email_le.setObjectName("email_le")
        self.horizontalLayout.addWidget(self.email_le)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.search_btn = QtWidgets.QPushButton(parent=Dialog)
        self.search_btn.setObjectName("search_btn")
        self.verticalLayout.addWidget(self.search_btn)
        self.answer_lb = QtWidgets.QLabel(parent=Dialog)
        self.answer_lb.setText("")
        self.answer_lb.setObjectName("answer_lb")
        self.verticalLayout.addWidget(self.answer_lb)
        self.close_btn = QtWidgets.QPushButton(parent=Dialog)
        self.close_btn.setObjectName("close_btn")
        self.verticalLayout.addWidget(self.close_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter the email"))
        self.search_btn.setText(_translate("Dialog", "Search"))
        self.close_btn.setText(_translate("Dialog", "Close"))
