# Form implementation generated from reading ui file '/Users/dima/PycharmProjects/LoginSystem/widget/DialogLoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogLoginWindow(object):
    def setupUi(self, DialogLoginWindow):
        DialogLoginWindow.setObjectName("DialogLoginWindow")
        DialogLoginWindow.resize(408, 382)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(DialogLoginWindow)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(parent=DialogLoginWindow)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(144, 23, 255);\n"
"color: rgb(235, 255, 0);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_6 = QtWidgets.QLabel(parent=DialogLoginWindow)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.info_lb = QtWidgets.QLabel(parent=DialogLoginWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.info_lb.setFont(font)
        self.info_lb.setStyleSheet("background-color: rgb(190, 255, 0);\n"
"background-color: rgb(231, 255, 179);")
        self.info_lb.setObjectName("info_lb")
        self.verticalLayout_4.addWidget(self.info_lb)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(parent=DialogLoginWindow)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.login_le_3 = QtWidgets.QLineEdit(parent=DialogLoginWindow)
        self.login_le_3.setObjectName("login_le_3")
        self.horizontalLayout_5.addWidget(self.login_le_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(parent=DialogLoginWindow)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.pass_le_3 = QtWidgets.QLineEdit(parent=DialogLoginWindow)
        self.pass_le_3.setObjectName("pass_le_3")
        self.horizontalLayout_6.addWidget(self.pass_le_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.logIn_btn = QtWidgets.QPushButton(parent=DialogLoginWindow)
        self.logIn_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.logIn_btn.setStyleSheet("background-color: rgb(144, 23, 255);\n"
"")
        self.logIn_btn.setObjectName("logIn_btn")
        self.verticalLayout_4.addWidget(self.logIn_btn)
        self.forgot_btn = QtWidgets.QPushButton(parent=DialogLoginWindow)
        self.forgot_btn.setStyleSheet("color: rgb(0, 0, 255);")
        self.forgot_btn.setFlat(True)
        self.forgot_btn.setObjectName("forgot_btn")
        self.verticalLayout_4.addWidget(self.forgot_btn)
        self.label_5 = QtWidgets.QLabel(parent=DialogLoginWindow)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.signUp_btn = QtWidgets.QPushButton(parent=DialogLoginWindow)
        self.signUp_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.signUp_btn.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.signUp_btn.setObjectName("signUp_btn")
        self.verticalLayout_4.addWidget(self.signUp_btn)

        self.retranslateUi(DialogLoginWindow)
        QtCore.QMetaObject.connectSlotsByName(DialogLoginWindow)

    def retranslateUi(self, DialogLoginWindow):
        _translate = QtCore.QCoreApplication.translate
        DialogLoginWindow.setWindowTitle(_translate("DialogLoginWindow", "Dialog"))
        self.label_10.setText(_translate("DialogLoginWindow", "           LoginSystemProject"))
        self.label_6.setText(_translate("DialogLoginWindow", "                                     Log into Project"))
        self.info_lb.setText(_translate("DialogLoginWindow", "                      Enter login and password to continue"))
        self.label_8.setText(_translate("DialogLoginWindow", "       Login"))
        self.label_9.setText(_translate("DialogLoginWindow", "Password"))
        self.logIn_btn.setText(_translate("DialogLoginWindow", "Log In"))
        self.forgot_btn.setText(_translate("DialogLoginWindow", "  Forgot account?"))
        self.label_5.setText(_translate("DialogLoginWindow", "                                                or"))
        self.signUp_btn.setText(_translate("DialogLoginWindow", "      Sign up for Project"))
