# Form implementation generated from reading ui file '/Users/dima/PycharmProjects/LoginSystem/widget/OpenWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 464)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 40, 261, 61))
        self.label.setObjectName("label")
        self.userData_lb = QtWidgets.QLabel(parent=self.centralwidget)
        self.userData_lb.setGeometry(QtCore.QRect(30, 100, 60, 16))
        self.userData_lb.setObjectName("userData_lb")
        self.name_lb = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_lb.setGeometry(QtCore.QRect(30, 130, 60, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lb.sizePolicy().hasHeightForWidth())
        self.name_lb.setSizePolicy(sizePolicy)
        self.name_lb.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.name_lb.setScaledContents(False)
        self.name_lb.setObjectName("name_lb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "You entered correct login and password"))
        self.userData_lb.setText(_translate("MainWindow", "info:"))
        self.name_lb.setText(_translate("MainWindow", "dffddffddfdfdf"))
